### ISSUE TITLE
Showing selected values on load and ReferenceError: key is not defined error

### ISSUE THREAD

**Issue by stibay** [scania-bootstrap/scania-angular-select2#2]
Got the  key is not defined error on line 64.
var selectedId = selectedItem[key];
Don't know if this should be changed to: var selectedId = selectedItem["id"]; ? Worked then atleast.

I am also having some issues showing the selected values on load. If I just set at static list and selected values inside the controller it works fine.

But I am using this with SignalR and on page load it fires up a hub which calls $scope.hubProxy.client.all method after the hub is started (this calls a OnConnected method on the server which gets the selected list and values).

The method simply looks like this:

```
$scope.hubProxy.client.all = function (team, users) {
    $scope.items = users;
    $scope.selectedItems = team;
}
```

I changed to using $scope instead of the vm variable and I can see it sets the selected values on load because I cannot select them in the dropdown and they are beeing sent to the change method.

**Comment by stibay** [comment]
Nice! That bugfix seems to have solved both issues :)

**Comment by mohammed-softordi** [comment]
Hi @stibay!

I released a patch that fixe among other the bug you reported. You hade an old version of scania-angular-select2, so update to this version and evrything should work fine.

**Comment by stibay** [comment]
Perfect, thank you.

**Comment by mohammed-softordi** [comment]
Any time, thanks for reporting.

**Comment by mohammed-softordi** [comment]
Yes, sorry I forgot to mention that. Now the directive support $primes, matcher and other directives (you can e.g. use a localized placeholder with a i18n directive on the sc-select2, or other directive)
