### ISSUE TITLE
Event on search input

### ISSUE THREAD

**Issue by stibay** [scania-bootstrap/scania-angular-select2#4]
Hi.

Is it possible to have an event function on search input.
I want to try and use this for serverside autocomplete and since it's around 20 000 records in the list it slows the browser when all is beeing added to the list (even if I use the data-minimum-input-length parameter etc)

**Comment by mohammed-softordi** [comment]
Hello, I've just pushed a patch that should solve your problem, hope is not too late. I will release a new version after lunch :-).
 I updated the docs with details on how to listen to the event emitted when the user enter a search key.

**Comment by stibay** [comment]
Thanks alot. Have been really busy lately but I will update and test this.

**Comment by stibay** [comment]
Can't get this to work. Could you show an example on how to use it? Can't see that you have updated the docs.

**Comment by scania-bootstrap** [comment]
Hello,
We will shortly remove this GitHub account. Please Fork the projects that you would like to keep before the end of this week.

Best regards,

Jesper Karlsson
jesper.karlsson@scania.commailto:jesper.karlsson@scania.com
