### ISSUE TITLE
Select not cleared when ng-model set to null from outside

### ISSUE THREAD

**Issue by dockinkong** [scania-bootstrap/scania-angular-select2#6]
Hello,

When updating my model from outside, resetting it for example, select still show previous selection.

Could it be possible to replace 
`// Access ngModel, $attr.multiple, select, options.value,
                function updateSelectedItemsOnDisplay() {
                    if (!$scope.ngModel) return;`

by
`// Access ngModel, $attr.multiple, select, options.value,
                function updateSelectedItemsOnDisplay() {
                    if (!$scope.ngModel) {
                        $timeout(function () { 
                            $(element).select2("val", "");
                        });
                        return;
                    }`

Regards,

**Comment by mohammed-softordi** [comment]
Sorry for the late reply. You still having problem updating ng-model outside the scope? We've made some major changes witch may fix your problem. Try updating to the latest version. 
This repos will soon be migrated to an internal Git Enterprise repos and will not be accessible from outside Scania. You should consider storing this library localy. I will hold a copy for this on my account but the support will probabilly be limited.

**Comment by abhi3460** [comment]
hello,

When selecting any items, how do i get selected options. ng-change is not working with it.

I can't get selected options in single or multiple also. i have to use both.

So, please help me.
