### ISSUE TITLE
Can't get selected options from select input.

### ISSUE THREAD

**Issue by abhi3460** [scania-bootstrap/scania-angular-select2#7]
hello,

When selecting any items, how do i get selected options. ng-change is not working with it.

I can't get selected options in single or multiple also. i have to use both.

So, please help me.

Thank you.

**Comment by mohammed-softordi** [comment]
Hi,

On both single and multiselect you can get the selected option(s) on the `ng-model` attribute or in the `ng-change` event.


<select id="my-multi" multiple="multiple" 
                   ng-options="item as item.name for item in vm.items track by item.id"
                   **ng-change="vm.selectionChanged(item)"**
                   **ng-model="vm.selectedItems"**
                    data-value="id" 
                    sc-multi-select>
       </select>

Hope this will help, happy new year! :smile:
